#!/usr/bin/env python3
"""
Job Monitor - Setup Script

Interactive setup to configure your job monitoring system.
"""

import os
import sys

def setup():
    """Interactive setup wizard."""
    
    print("\n" + "="*70)
    print("JOB MONITOR - SETUP WIZARD")
    print("="*70 + "\n")
    
    print("This wizard will help you configure your job monitoring system.\n")
    
    # Email configuration
    print("📧 EMAIL CONFIGURATION")
    print("-" * 70)
    email_from = input("Gmail address to send from: ").strip()
    
    print("\nTo get a Gmail App Password:")
    print("1. Go to: https://myaccount.google.com/apppasswords")
    print("2. Select 'Mail' and 'Other'")
    print("3. Copy the 16-character password")
    email_password = input("\nGmail App Password: ").strip()
    
    email_to = input("Email address to receive alerts (can be same): ").strip()
    
    # Search criteria
    print("\n\n🔍 SEARCH CRITERIA")
    print("-" * 70)
    print("Enter job keywords (comma-separated)")
    print("Example: Credit Analyst,Summer Analyst,Corporate Banking")
    keywords = input("Keywords: ").strip()
    if not keywords:
        keywords = "Credit Analyst,Summer Analyst,Corporate Banking,Investment Analyst"
    
    print("\nEnter target locations (comma-separated)")
    print("Example: Seattle,San Francisco,New York,Remote")
    locations = input("Locations: ").strip()
    if not locations:
        locations = "Seattle,Bellevue,San Francisco,Remote"
    
    print("\nEnter keywords to EXCLUDE (comma-separated)")
    print("Example: Senior,Manager,Director")
    exclude = input("Exclude: ").strip()
    if not exclude:
        exclude = "Senior,Manager,Director,VP"
    
    print("\nEnter target companies (comma-separated)")
    print("Example: Wells Fargo,JPMorgan,BMO")
    companies = input("Companies: ").strip()
    if not companies:
        companies = "Wells Fargo,JPMorgan Chase,BMO,KeyBank,Bank of America"
    
    print("\nMinimum score to trigger alert (0-15, recommended: 3)")
    min_score = input("Min score: ").strip()
    if not min_score:
        min_score = "3"
    
    # Create .env file
    env_content = f"""# Job Monitor Configuration
# Generated by setup script

# Email Settings
EMAIL_FROM={email_from}
EMAIL_PASSWORD={email_password}
EMAIL_TO={email_to}

# Search Parameters
KEYWORDS={keywords}
LOCATIONS={locations}
EXCLUDE_KEYWORDS={exclude}

# Scoring Thresholds
MIN_SCORE={min_score}

# Companies to Monitor
COMPANIES={companies}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n\n✅ Configuration saved to .env")
    
    # Test email
    print("\n\n📧 TESTING EMAIL")
    print("-" * 70)
    test = input("Send test email? (y/n): ").strip().lower()
    
    if test == 'y':
        print("\nSending test email...")
        from utils.emailer import send_test_email
        from utils.database import init_database
        
        init_database()
        
        if send_test_email():
            print("✅ Test email sent successfully!")
        else:
            print("❌ Test email failed. Check your Gmail settings.")
    
    # Next steps
    print("\n\n🚀 NEXT STEPS")
    print("="*70)
    print("\n1. Run manually to test:")
    print("   python main.py")
    print("\n2. Deploy to GitHub Actions:")
    print("   - Push this repo to GitHub")
    print("   - Add secrets from .env to repository settings")
    print("   - Enable GitHub Actions")
    print("\n3. Or run locally on schedule:")
    print("   - Add to crontab: 0 */6 * * * cd $(pwd) && python main.py")
    
    print("\n" + "="*70)
    print("Setup complete! 🎉")
    print("="*70 + "\n")

if __name__ == '__main__':
    try:
        setup()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
